### ISSUE TITLE
Status of the repo?

### ISSUE THREAD

**Issue by purohit** [drone/go.stripe#19]
Hi there,

I'm just checking if the library is still being maintained, and if so, if we should use bradrydzewski's version or drone.io's version.

Thanks!

**Comment by elithrar** [comment]
@purohit I can't speak directly for Drone.io, but they have been responding to PRs/issues and the commit list shows active commits: https://github.com/drone/go.stripe/commits/master

Note that libraries like these don't always see "weekly" commits since they are tied to a stable API (in this case, Stripe's).

**Comment by purohit** [comment]
Thanks for answering, makes sense that it wouldn't change frequently. I submitted a pull request to change the import path in the README since it still lists bradrydzewski's version instead of drone.io's.
